
import { marked } from 'marked';

/**
 * Converts Markdown content to HTML and copies it to the clipboard as Rich Text.
 * Then opens a new Google Doc for the user to paste.
 */
export const exportToGoogleDocs = async (markdownContent: string, title: string = "Analysis Report") => {
  try {
    // 1. Convert Markdown to HTML
    const htmlFragment = await marked.parse(markdownContent);

    // 2. Wrap in a full HTML structure with Google Docs-friendly styles
    const fullHtml = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>${title}</title>
        <style>
          body { 
            font-family: 'Arial', sans-serif; 
            font-size: 11pt; 
            line-height: 1.5; 
            color: #000000;
            background-color: #ffffff;
          }
          h1 { 
            font-size: 24pt; 
            font-weight: bold; 
            color: #000000; 
            margin-top: 24pt; 
            margin-bottom: 12pt;
            border-bottom: 1px solid #eeeeee;
            padding-bottom: 6pt;
          }
          h2 { 
            font-size: 18pt; 
            font-weight: bold; 
            color: #202124; 
            margin-top: 18pt; 
            margin-bottom: 8pt; 
          }
          h3 { 
            font-size: 14pt; 
            font-weight: bold; 
            color: #434343; 
            margin-top: 14pt; 
            margin-bottom: 6pt; 
          }
          p { 
            margin-bottom: 12pt; 
          }
          ul, ol { 
            margin-bottom: 12pt; 
            padding-left: 20pt;
          }
          li { 
            margin-bottom: 4pt; 
          }
          strong { 
            font-weight: bold; 
            color: #202124;
          }
          blockquote { 
            border-left: 3px solid #ccc; 
            padding-left: 12pt; 
            color: #5f6368; 
            font-style: italic; 
            margin-left: 0;
            margin-right: 0;
          }
          code { 
            background-color: #f1f3f4; 
            padding: 2px 4px; 
            border-radius: 3px; 
            font-family: 'Courier New', monospace; 
            font-size: 10pt; 
          }
          table {
            border-collapse: collapse;
            width: 100%;
            margin-bottom: 12pt;
          }
          th, td {
            border: 1px solid #dadce0;
            padding: 8pt;
            text-align: left;
          }
          th {
            background-color: #f1f3f4;
            font-weight: bold;
          }
        </style>
      </head>
      <body>
        ${htmlFragment}
        <br><br>
        <p style="font-size: 9pt; color: #999; text-align: center;">Generated by HOSEA's Inspiration Pocket AI</p>
      </body>
      </html>
    `;

    // 3. Create Blob objects
    const blobHtml = new Blob([fullHtml], { type: 'text/html' });
    const blobText = new Blob([markdownContent], { type: 'text/plain' });

    // 4. Write to Clipboard
    const data = [new ClipboardItem({
      'text/html': blobHtml,
      'text/plain': blobText
    })];

    await navigator.clipboard.write(data);

    // 5. Open Google Docs
    window.open('https://docs.new', '_blank');

  } catch (err) {
    console.error('Export failed:', err);
    // Fallback: Copy plain text if HTML copy fails
    try {
        await navigator.clipboard.writeText(markdownContent);
        alert("格式化复制失败，已复制纯文本。请在打开的文档中粘贴 (Ctrl+V)。");
        window.open('https://docs.new', '_blank');
    } catch (e) {
        alert("复制失败，请手动复制内容。");
    }
  }
};
